# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='编号')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'TYPE 0'), (1, 'TYPE 1'), (2, 'TYPE 2')], null=True, verbose_name='型号')),
                ('ppoi', versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True, verbose_name='关键点')),
                ('qr', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='qr', verbose_name='二维码')),
            ],
            options={
                'verbose_name': '机器',
                'verbose_name_plural': '机器',
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='闭合')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='释放')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '电压'), (1, '电流'), (2, '电阻'), (3, '时间')], null=True, verbose_name='类型')),
                ('time_joined', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('machine', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='机器')),
            ],
            options={
                'verbose_name': '继电器测试',
                'verbose_name_plural': '继电器测试',
                'db_table': 'relay',
            },
        ),
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='闭合')),
                ('open', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='释放')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '电压'), (1, '电流'), (2, '电阻'), (3, '时间')], null=True, verbose_name='类型')),
                ('time_joined', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('machine', models.CharField(blank=True, max_length=50, null=True, verbose_name='机器')),
            ],
            options={
                'verbose_name': '触点测试',
                'verbose_name_plural': '触点测试',
                'db_table': 'touch',
            },
        ),
    ]
